version: "3.6"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - "./:/var/www/html/"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./var/log/nginx/:/var/log/nginx"
    ports:
      - "8000:80"
    networks:
      - backend

  php:
    image: php:7.2-fpm-alpine
    volumes:
      - "./:/var/www/html/"
    networks:
      - backend

networks:
  backend:
