version: "3.7"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - "./:/var/www/html/"
      - "./docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./var/log/nginx/:/var/log/dev/nginx"
    ports:
      - "8000:80"
    networks:
      - backend

  php:
    image: oneguard/php:7.2-fpm-xdebug
    volumes:
      - "./:/usr/src/app/"
    networks:
      - backend

  assets:
    image: node:alpine
    volumes:
      - "./:/usr/src/app/"

networks:
  backend:
